# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

jobs:
  build:
    working_directory: /
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker file
          command: |
            docker build . -t app
      - run:
          name: Run docker
          command: |
            docker run -d --name instance
            docker run --network container:instance appropriate/curl --retry 10 --retry-connrefused http://localhost:8080

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  building:
    jobs:
      - build
